version: '3.2'
services:
  grafana:
    image: grafana/grafana
    restart: always
    container_name: grafana
    depends_on:
    - prometheus
    ports:
    - 3000:3000
    volumes: 
    - grafana-config:/etc/grafana:rw
    - grafana-data:/var/lib/grafana:rw
    - grafana-home:/usr/share/grafana:rw
    environment:
      GF_SERVER_ROOT_URL: https://grafanatest.com
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,raintank-worldping-app
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./:/etc/prometheus/:rw
    - prometheus-volume:/prometheus-grafana:rw
    depends_on:
    - cadvisor
    - alertmanager
 #   - node_exporter
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    cap_add: 
    - SYS_TIME
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
  alertmanager: 
    image: quay.io/prometheus/alertmanager
    container_name: alertmanager
    volumes: 
    - ./alertmanager/:/etc/alertmanager/:rw
    - alertmanager-volume:/alertmanager/:rw
    ports: 
    - 9093:9093
    command: 
    - --config.file=/etc/alertmanager/alertmanager.yml
  #node_exporter: 
  #    image: quay.io/prometheus/node-exporter
  #    container_name: node_exporter
  #    volumes:
  #    - /:/host:ro,rslave
  #    ports: 
  #    - 9100:9100
  #    cap_add: 
  #    - SYS_TIME

volumes:
  prometheus-volume:
  alertmanager-volume:
  grafana-config:
  grafana-data:
  grafana-home: